ACCESS_TOKEN: None # Add your model API token here
MODEL_NAME: gpt-3.5-turbo
DATASET_NAME: WikiText
VECTORSTORE_NAME: LangchainFAISS
SEARCH_TYPE: similarity
TOKEN_LIMIT: 2000
N_RETRIEVED_DOCS: 5
SAVE_PATH: document_store/
LOG_PATH: logs/
PATTERNS_FILENAME: src/config/manipulate_patterns.json
VERBOSE: true
